name: benchmark
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  system_monitor: ^1.0.6
  fl_chart: ^0.69.0
  permission_handler: ^11.3.1
  ffi: ^2.1.3
  device_info_plus: ^11.1.0
  semicircle_indicator: ^1.1.1
  provider: ^6.1.2
  # progress_bar_chart: ^0.0.12
  flutter_storage_info: ^0.0.5
  flutter_animate:
  flex_color_scheme: ^7.3.1
  network_info_plus: ^6.1.0
  connectivity_plus: ^6.1.0
  rxdart: ^0.28.0
  better_cpu_reader:
    git:
      url: https://github.com/exoad/better_cpu_reader.git
  pie_chart: ^5.4.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
